---
sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
jobs:
  include:
    - stage: Lint & Test
      script: ./hack/gotest.sh
      name: Installer unit tests
    - script: ./hack/go-lint.sh installer/...
      name: Go lint
