---
sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
jobs:
  include:
    - stage: Lint & Test
      script: ./hack/gotest.sh
      name: Installer unit tests
    - script: "docker run -v $PWD:$PWD -w $PWD quay.io/coreos/golang-testing golint -set_exit_status installer/..."
      name: Go lint
